Product
BANCUNGUYE66/budget-app pull request #1
Opened 2023-09-14 16:28 UTC by BANCUNGUYE66

### In this PR i completed the following
 Splash screen
 
 * A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
 
 Sign up and log in pages
 
 * The user should be able to register in the app with full name, email and password (all mandatory).
 * The user can log into the app using email and password.
 * If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
 
 Home page (categories page)
 
 * When the user logs in, they are presented with the categories page.
 * For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
 * When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
 * There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
 
 Transactions page
 
 * For a given category, the list of transactions is presented, ordered by the most recent.
 * At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
 * There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
 * When the user clicks on the "Back" button (<), the user navigates to the home page.
 
 "Add a new category" page

 * The user fills out a form to create a new category, indicating their name and icon (both mandatory).
 * The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
 * When the user clicks on the "Back" button (<), the user navigates to the home page.
 
 "Add a new transaction" page
 
  The user fills out a form to create a new transaction with:
 
 * name (mandatory)
 * amount (mandatory)
 * categories (mandatory at least one)
 
 The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
 
 When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
 
 Testing requirements
 
 * Create unit and integration tests for all the most important components of your RoR application.

2023-09-14 17:21 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

![invalid-submission](https://user-images.githubusercontent.com/93039359/221218445-05489541-f840-492c-878e-0587cc2b3702.gif)

## Hey @BANCUNGUYE66 :wave:

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Mandatory Changes ♻️

- [ ] It would be nice if you fix the migrations because I am not able to run the migrations 😨 Kindly fix them and submit this pull request again 👍

2023-09-14 19:24 UTC, BANCUNGUYE66 commented
@HAMMAS-SALEEM Thank you for your review time, but in my project, everything is working well as you can check in the presentation video in the README file.

2023-09-14 22:49 UTC, Munsa1 requested changes
Hi @BANCUNGUYE66, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
## Highlights
Good Job On The Video Presentation :heavy_check_mark: 
Used Devise For Authentication :heavy_check_mark: 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-14 22:49 UTC, Munsa1 commented on app/views/devise/sessions/new.html.erb
> +</div>
- [ ] Good job on the mobile design, however, we need to follow the given design for the Login and Sign up pages, including the colors, layout, and typography.


Your design
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/e4dbc1b8-4767-459e-a97a-52054927bdcf)

![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/9c24829e-78a5-49bc-8370-53fba6bc1edb)

![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/fcc3d983-e717-4a6a-9e8f-63b7dd96fa58)


Given design
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/8f3a9b96-7bdb-4f21-8d77-7cc967dec746)

![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/3aa90154-89a0-43b8-bdd7-a93f2eab0c13)

![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/e0d6c5af-d8e2-455a-9e36-36c9047b4d70)


- Kindly fix the color of the button in your design
- Also kindly follow the given layout in your design
- Kindly use the correct font family for your design, you have used `Poppins` whilst the given font is `Proxima Nova Bold`

### Note that the font family layout and design applies to the entire application

2023-09-14 22:49 UTC, Munsa1 commented on README.md
> +## 🚀 Live Demo <a name="live-demo" ></a>
- [ ] It is a requirement that you deploy your app using Render, GitHub pages, or Netlify, kindly do so and add the live link to the `Live Demo` section of your readme file

2023-09-14 22:49 UTC, Munsa1 commented on app/views/entities/index.html.erb
> +</div>
- [ ] Kindly follow the given design for this page as well as per requirements.

Your design
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/46b4d050-19b3-4fcb-aa5d-6798e4c6349a)

Given design
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/5cc719f0-a085-460f-a275-843f61f88908)

- Kindly ensure you follow the layout of elements on your page to match the given design

2023-09-14 22:49 UTC, Munsa1 commented on db/migrate/20230912104205_create_groups.rb
> +      t.references :author, null: false, foreign_key: { to_table: :users }
- [ ] Kindly add indexes for all your foreign keys as per requirement

2023-09-15 07:11 UTC, Munsa1 commented
- [ ] Kindly add an MIT License Agreement to your readme file, for a more professional readme file
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/07ea3ad0-3cae-444d-998d-9d64ac3aa015)

- [ ] Also ensure that the issues link points to this project's issues page and not to another capstone under the Contributing section of your readme file
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/734911a5-af7b-497e-8c82-37327480b51a)

![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/734a3e40-da2e-4394-817d-8d2bf2da7536)


- [ ] Lastly, kindly fix the link to your `LinkedIn` profile under the Author section of your readme file as it is a broken link leading nowhere
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/b343e9b3-7137-4b74-a4a1-23e5177e6207)

2023-09-15 07:43 UTC, Munsa1 commented
- [ ] Kindly fix the broken link to the `Tech Stack` under the built-with section by adding a subheading so that when the user clicks on this link they get taken to the tech stack. This will make the readme file more professional.
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/b4a23979-83c2-45a8-81eb-1cc2665ee5bc)

Clicking on the link above should take the user to part below
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/9f055c5e-95d3-4d0f-8842-01c81da0e462)

- [ ] Also consider fixing the following broken links in the table of contents pointing to subsections of the `Getting Started` section
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/edfa947c-f645-401f-bc85-6df643b9c508)
![image](https://github.com/BANCUNGUYE66/budget-app/assets/81932478/a57ddb7b-32b9-4262-a223-30f6b053f01f)

2023-09-19 16:19 UTC, Alfredbis29 reviewed
Hi @BANCUNGUYE66  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has already the request changes and i\on my sdie is the first  review, kindly open another PR and request for another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-19 18:29 UTC, closed without merging